SELECT
    PROVIDER_ID,
    MEASURE_ID,
    ANSWER_PERCENT,
    LINEAR_MEAN_VALUE,
    PATIENT_SURVEY_STAR_RATING,
    NUMBER_OF_COMPLETED_SURVEYS,
    SURVEY_RESPONSE_RATE_PERCENT,
    PATIENT_SURVEY_STAR_RATING_FOOTNOTE,
    NUMBER_OF_COMPLETED_SURVEYS_FOOTNOTE, 
    SURVEY_RESPONSE_RATE_PERCENT_FOOTNOTE,
    ANSWER_PERCENT_FOOTNOTE,
    MEASURE_START_DATE,
    MEASURE_END_DATE
FROM {{ ref('stg_patient_survey') }}